baseURL = "/"
title = "FreeCONF"

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
enableGitInfo = true
staticDir = ['static']

[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
taxonomyCloud = ["tags", "categories"] 
taxonomyCloudTitle = ["Tag Cloud", "Categories"] 
taxonomyPageHeader = ["tags", "categories"] 

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "monokai"

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

[languages]
[languages.en]
title = "FreeCONF"
description = "A Software Management Library"
languageName ="English"
weight = 1


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "catppuccin-mocha"

[outputs]
section = ["HTML", "print", "RSS"]

[params]
copyright = "The FreeCONF Authors"
archived_version = false
version = "0.0"
url_latest_version = "https://example.com"

github_project_repo = "https://github.com/freeconf/restconf"
algolia_docsearch = false
offlineSearch = false
prism_syntax_highlighting = false

[params.ui]
breadcrumb_disable = false
footer_about_disable = false
navbar_logo = true
navbar_translucent_over_cover_disable = false
sidebar_menu_compact = false
sidebar_search_disable = false

[params.ui.feedback]
enable = false

[params.ui.readingtime]
enable = false

[params.links]
[[params.links.user]]
  name = "Discussion Forum"
  url = "https://github.com/orgs/freeconf/discussions"
  icon = "fa fa-envelope"
  desc = "Discussion and help from your fellow users"

[params.mermaid]
enable = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.75.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

